# Generated by Django 5.1.7 on 2025-12-01 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('category', models.CharField(choices=[('mountain', 'Горные велосипеды'), ('road', 'Шоссейные велосипеды'), ('city', 'Городские и прогулочные велосипеды')], max_length=50, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images/', verbose_name='Изображение')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created'],
            },
        ),
    ]
